__version__:
  serializer: 1
  data: 7
Settings:
  Acquisitions:
    - Acquisition:
        Aperture: 6.18948814535263
        Brightness: 1.8
        ExposureTime: 6500
        Gain: 1.00361254147337
    - Acquisition:
        Aperture: 3.44969033698656
        Brightness: 1.8
        ExposureTime: 6500
        Gain: 1.60981037877997
    - Acquisition:
        Aperture: 2.59019927037542
        Brightness: 1.8
        ExposureTime: 6500
        Gain: 3.05285068572685
    - Acquisition:
        Aperture: 2.27527749426455
        Brightness: 1.8
        ExposureTime: 13000
        Gain: 3.96176546148286
  Experimental:
    Engine: phase
  Processing:
    Color:
      Balance:
        Blue: 1
        Green: 1
        Red: 1
      Gamma: 1
    Filters:
      Experimental:
        ContrastDistortion:
          Correction:
            Enabled: no
            Strength: 0.4
          Removal:
            Enabled: no
            Threshold: 0.5
      Noise:
        Removal:
          Enabled: yes
          Threshold: 7
      Outlier:
        Removal:
          Enabled: yes
          Threshold: 5
      Reflection:
        Removal:
          Enabled: yes
      Smoothing:
        Gaussian:
          Enabled: yes
          Sigma: 1.5