__version__:
  serializer: 1
  data: 7
Settings:
  Acquisitions:
    - Acquisition:
        Aperture: 11.31
        Brightness: 1.8
        ExposureTime: 20000
        Gain: 1
    - Acquisition:
        Aperture: 5.66
        Brightness: 1.8
        ExposureTime: 20000
        Gain: 1
    - Acquisition:
        Aperture: 2.83
        Brightness: 1.8
        ExposureTime: 20000
        Gain: 2
  Experimental:
    Engine: phase
  Processing:
    Color:
      Balance:
        Blue: 1
        Green: 1
        Red: 1
      Gamma: 1
    Filters:
      Experimental:
        ContrastDistortion:
          Correction:
            Enabled: yes
            Strength: 0.4
          Removal:
            Enabled: no
            Threshold: 0.5
      Noise:
        Removal:
          Enabled: yes
          Threshold: 7
      Outlier:
        Removal:
          Enabled: yes
          Threshold: 5
      Reflection:
        Removal:
          Enabled: yes
      Smoothing:
        Gaussian:
          Enabled: yes
          Sigma: 1.5