__version__:
  serializer: 1
  data: 5
Settings:
  Acquisitions:
    - Acquisition:
        Aperture: 8.0
        Brightness: 1
        ExposureTime: 10000
        Gain: 1
    - Acquisition:
        Aperture: 4.0
        Brightness: 1
        ExposureTime: 10000
        Gain: 1
    - Acquisition:
        Aperture: 4.0
        Brightness: 1
        ExposureTime: 40000
        Gain: 2
  Processing:
    Color:
      Balance:
        Blue: 1
        Green: 1
        Red: 1
    Filters:
      Noise:
        Removal:
          Enabled: yes
          Threshold: 7
      Experimental:
        ContrastDistortion:
          Correction:
            Enabled: yes
            Strength: 0.4
          Removal:
            Enabled: no
            Threshold: 0.5
      Outlier:
        Removal:
          Enabled: yes
          Threshold: 5
      Reflection:
        Removal:
          Enabled: yes
      Smoothing:
        Gaussian:
          Enabled: yes
          Sigma: 1.5