__version__:
  serializer: 1
  data: 6
Settings:
  Acquisitions:
    - Acquisition:
        Aperture: 4.0
        Brightness: 1.8
        ExposureTime: 2000
        Gain: 1
    - Acquisition:
        Aperture: 2.0
        Brightness: 1.8
        ExposureTime: 20000
        Gain: 1
  Processing:
    Color:
      Balance:
        Blue: 1
        Green: 1
        Red: 1
      Gamma: 1
    Filters:
      Noise:
        Removal:
          Enabled: yes
          Threshold: 5
      Experimental:
        ContrastDistortion:
          Correction:
            Enabled: yes
            Strength: 0.4
          Removal:
            Enabled: no
            Threshold: 0.5
      Outlier:
        Removal:
          Enabled: yes
          Threshold: 15
      Reflection:
        Removal:
          Enabled: yes
      Smoothing:
        Gaussian:
          Enabled: yes
          Sigma: 1.0
